### ISSUE TITLE
Necrobot client for pokemon go stopped (v0.9.1)

### ISSUE THREAD

**Issue by plasmasoul** [NoxxDev/NecroBot#194]
After autoupdate it shows this message and then closes.

[18:41:41] () Exception caught, writing LogBuffer.

Excepción no controlada: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en PoGo.NecroBot.Logic.LogicSettings.get_TranslationLanguageCode() en E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Settings.cs:línea 1354
   en PoGo.NecroBot.Logic.Common.Translation.Load(ILogicSettings logicSettings, Translation translations) en E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Common\Translations.cs:línea 885
   en PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) en E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:línea 35
   en PoGo.NecroBot.CLI.Program.Main(String[] args)

I don't know what's all that about but meanwhile I'll go back to 0.9.0 (Sorry for not being able to translate the error message to english but I don't know the error in english)

**Comment by vlalo001** [comment]
Are you using config from 0.9.0 or did you make a brand new config using 0.9.1 and an empty config folder?

**Comment by plasmasoul** [comment]
I moved my 0.9.0 config to other folder before opening the exe to create a brand new config and then modify it but after creating the json files and open it again it shows me that message

**Comment by vlalo001** [comment]
Ok, I recreated your issue. It's a bug with config file. You need to delete/rename "config.json" file in your "config" folder.

Then, you must run NecroBot.exe and setup a new config by following the steps.

I'll check this issue out tonight in more detail. But for now, this is one way to fix it.

**Comment by de81815** [comment]
08:06:42] Potential Evolutions: 0
[08:06:42] Incubator status update: 5.05km left
[08:06:44] Amount of Pokemon Seen: 110/151, Amount of Pokemon Caught: 110/151
[08:07:29] Pokemon Servers might be offline / unstable. Trying again...
[08:07:30] Error: System.Xml.XmlException: 遺漏根元素。
   於 System.Xml.XmlTextReaderImpl.Throw(Exception e)
   於 System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   於 System.Xml.XmlTextReaderImpl.Read()
   於 System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   於 System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   於 PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(GeoCoordinate start, GeoCoordinate dest) 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs: 行 24
   於 PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs: 行 17
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass5_0.<GetPokeStops>b__1(FortData i) 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 274
   於 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<GetPokeStops>d__5.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 271
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 62
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs: 行 68
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs: 行 56

**Comment by uncannierelf** [comment]
[19:13:38] Pokemon Servers might be offline / unstable. Trying again...
[19:13:39] Error: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 144.76.224.55:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(GeoCoordinate start, GeoCoordinate dest) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 24
   at PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 17
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56

**Comment by tr1p0z** [comment]
What happened :-1:

**Comment by plasmasoul** [comment]
I tried a couple of times and now I made the bot works but after getting the (info)amount seen and caught it shows me the @uncannierelf error message.

**Comment by robzork** [comment]
bot dont work ... do u know next reales?

**Comment by rjcute123** [comment]
same error here

**Comment by hybridcore09** [comment]
Same error here. :'(

**Comment by robzork** [comment]
yes do u know if account banned ? i come from france . dont know how many times to realeses ... ? cant found pokestop or pokemon , i am not good on computeur to fix that

**Comment by matden00** [comment]
same goes to me. what happen? good thing it was not a permanent ban,

**Comment by robzork** [comment]
i am not ban , but the bot dont work . do u know how many  times to have a realeses ?

**Comment by NoxxDev** [comment]
Fixed in release [v0.9.2] (https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.2)

**Comment by robzork** [comment]
when ?
