### ISSUE TITLE
An exception after auto upgrade

### ISSUE THREAD

**Issue by Festum** [NoxxDev/NecroBot#213]
Encounter this error when bot started
```
[11:07:56] () Exception caught, writing LogBuffer.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.LogicSettings.get_TranslationLanguageCode() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 1369
   at PoGo.NecroBot.Logic.Common.Translation.Load(ILogicSettings logicSettings, Translation translations) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Common\Translations.cs:line 887
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 35
   at PoGo.NecroBot.CLI.Program.Main(String[] args)
```

**Comment by thib3113** [comment]
The same for me .

Windows 10 64bits French

**Comment by Festum** [comment]
Seems trasfer config after update failed.
