### ISSUE TITLE
False positive softban in 0.9.0 - behavior flaw

### ISSUE THREAD

**Issue by goshslayer** [NoxxDev/NecroBot#216]
sometimes the bot take a pokestop and try to recatch it as "next pokestop", leading to spamming SOFTBAN on a deactivated pokestop for 5 minutes.

**Comment by goshslayer** [comment]
[05:09:13] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:19] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:26] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:32] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:37] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:43] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:47] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:54] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:09:59] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:10:05] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:10:27] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:10:32] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:10:36] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:10:43] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
. Unban in: 35/45
[05:10:49] (SOFTBAN) Successfully bypassed!
[05:10:49] (POKESTOP) Name: Topiary Golfer XP: 50, Gems: 0, Items: 4 x ItemPokeB
all, Lat: 52.555238, Long: -1.73222
[05:10:50] (EVOLVED) Potential Evolutions: 0
[05:10:52] (INFO) Amount of Pokemon Seen: 2/151, Amount of Pokemon Caught: 2/151

[05:10:54] (INFO) Traveling to Pokestop: Topiary Golfer (9m) (2 seconds)
[05:10:59] (PKMN) (CatchSuccess) | (Lure) Weedle Lvl: 1 CP: (10/10) IV: 31.00% |
 Chance: 100% | 5.26m dist | with a PokeBall (68 left). | 110 EXP earned | Candi
es: 3 | lat: 52.555238 long: -1.732220
[05:11:00] (TRANSFERRED) Weedle - CP: 10  IV: 30.82%   [Best CP: 10  IV: 32.30%]
 (Candies: 7)
[05:11:09] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:14] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:18] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:25] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:30] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:35] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:40] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:46] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:51] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:11:57] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:03] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:09] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:14] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:19] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:24] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:30] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:35] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:39] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:45] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:51] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:12:56] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:02] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:07] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:12] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:17] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:23] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:29] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:34] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:40] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:46] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:50] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:13:55] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:00] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:05] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:11] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:15] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:20] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:24] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:29] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:35] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:40] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:45] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:52] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:14:57] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:15:03] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
. Unban in: 45/45
[05:15:09] (EVOLVED) Potential Evolutions: 0
[05:15:11] (INFO) Amount of Pokemon Seen: 2/151, Amount of Pokemon Caught: 2/151

[05:15:11] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[05:15:12] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of r
ange. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argu
ment, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
[05:15:12] (INFO) Logging in using Ptc
[05:15:17] (INFO) Playing as bosis
[05:15:17] (ATTENTION) Detected realistic Traveling , using Default Settings ins
ide config.json
[05:15:17] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat:
52.5551920707003 Lng: -1.73220145124597
[05:15:18] (INFO) ====== DisplayHighestsCP ======
[05:15:18] (INFO) # CP   10/  10 | (43.79% perfect)     | Lvl 01         NAME: P
idgey            MOVE1: TackleFast           MOVE2: Twister              Candy:
3
[05:15:18] (INFO) # CP   10/  10 | (32.30% perfect)     | Lvl 01         NAME: W
eedle            MOVE1: PoisonStingFast      MOVE2: Struggle             Candy:
7
[05:15:18] (INFO) ====== DisplayHighestsPerfect ======
[05:15:18] (INFO) # CP   10/  10 | (43.79% perfect)     | Lvl 01         NAME: P
idgey            MOVE1: TackleFast           MOVE2: Twister              Candy:
3
[05:15:18] (INFO) # CP   10/  10 | (32.30% perfect)     | Lvl 01         NAME: W
eedle            MOVE1: PoisonStingFast      MOVE2: Struggle             Candy:
7
[05:15:18] (EVOLVED) Potential Evolutions: 0
[05:15:20] (INFO) Amount of Pokemon Seen: 2/151, Amount of Pokemon Caught: 2/151

[05:15:21] (INFO) Traveling to Pokestop: Topiary Golfer (5m) (1 seconds)
[05:15:25] (PKMN) (CatchSuccess) | (Lure) Kakuna Lvl: 2 CP: (18/21) IV: 51.00% |
 Chance: 60.1% | 0.00m dist | with a PokeBall (67 left). | 660 EXP earned | Cand
ies: 3 | lat: 52.555238 long: -1.732220
[05:15:32] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:15:39] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:15:44] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:15:49] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
. Unban in: 4/45
[05:15:53] (SOFTBAN) Successfully bypassed!
[05:15:53] (POKESTOP) Name: Topiary Golfer XP: 50, Gems: 0, Items: 3 x ItemPokeB
all, Lat: 52.555238, Long: -1.73222
[05:15:53] (EVOLVED) Potential Evolutions: 0
[05:15:54] (EGG) Putting egg in incubator: 2.00km left
[05:15:55] (INFO) Amount of Pokemon Seen: 3/151, Amount of Pokemon Caught: 3/151

[05:15:56] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[05:15:57] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of r
ange. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argu
ment, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
[05:15:57] (INFO) Logging in using Ptc
[05:16:01] (INFO) Playing as bosis
[05:16:01] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat:
52.5552380205095 Lng: -1.73222000828559
[05:16:01] (INFO) ====== DisplayHighestsCP ======
[05:16:01] (INFO) # CP   18/  21 | (50.59% perfect)     | Lvl 02         NAME: K
akuna            MOVE1: BugBiteFast          MOVE2: Struggle             Candy:
10
[05:16:01] (INFO) # CP   10/  10 | (43.79% perfect)     | Lvl 01         NAME: P
idgey            MOVE1: TackleFast           MOVE2: Twister              Candy:
3
[05:16:01] (INFO) # CP   10/  10 | (32.30% perfect)     | Lvl 01         NAME: W
eedle            MOVE1: PoisonStingFast      MOVE2: Struggle             Candy:
10
[05:16:01] (INFO) ====== DisplayHighestsPerfect ======
[05:16:01] (INFO) # CP   18/  21 | (50.59% perfect)     | Lvl 02         NAME: K
akuna            MOVE1: BugBiteFast          MOVE2: Struggle             Candy:
10
[05:16:01] (INFO) # CP   10/  10 | (43.79% perfect)     | Lvl 01         NAME: P
idgey            MOVE1: TackleFast           MOVE2: Twister              Candy:
3
[05:16:01] (INFO) # CP   10/  10 | (32.30% perfect)     | Lvl 01         NAME: W
eedle            MOVE1: PoisonStingFast      MOVE2: Struggle             Candy:
10
[05:16:02] (EVOLVED) Potential Evolutions: 0
[05:16:02] (EGG) Incubator status update: 2.00km left
[05:16:04] (INFO) Amount of Pokemon Seen: 3/151, Amount of Pokemon Caught: 3/151

[05:16:05] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[05:16:06] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of r
ange. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argu
ment, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
[05:16:06] (INFO) Logging in using Ptc
[05:16:10] (INFO) Playing as bosis
[05:16:10] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat:
52.5552380205095 Lng: -1.73222000828559
[05:16:10] (INFO) ====== DisplayHighestsCP ======
[05:16:10] (INFO) # CP   18/  21 | (50.59% perfect)     | Lvl 02         NAME: K
akuna            MOVE1: BugBiteFast          MOVE2: Struggle             Candy:
10
[05:16:10] (INFO) # CP   10/  10 | (43.79% perfect)     | Lvl 01         NAME: P
idgey            MOVE1: TackleFast           MOVE2: Twister              Candy:
3
[05:16:10] (INFO) # CP   10/  10 | (32.30% perfect)     | Lvl 01         NAME: W
eedle            MOVE1: PoisonStingFast      MOVE2: Struggle             Candy:
10
[05:16:10] (INFO) ====== DisplayHighestsPerfect ======
[05:16:10] (INFO) # CP   18/  21 | (50.59% perfect)     | Lvl 02         NAME: K
akuna            MOVE1: BugBiteFast          MOVE2: Struggle             Candy:
10
[05:16:10] (INFO) # CP   10/  10 | (43.79% perfect)     | Lvl 01         NAME: P
idgey            MOVE1: TackleFast           MOVE2: Twister              Candy:
3
[05:16:10] (INFO) # CP   10/  10 | (32.30% perfect)     | Lvl 01         NAME: W
eedle            MOVE1: PoisonStingFast      MOVE2: Struggle             Candy:
10
[05:16:10] (EVOLVED) Potential Evolutions: 0
[05:16:11] (EGG) Incubator status update: 2.00km left
[05:16:12] (INFO) Amount of Pokemon Seen: 3/151, Amount of Pokemon Caught: 3/151

[05:16:13] (INFO) Traveling to Pokestop: Topiary Golfer (0m) (0 seconds)
[05:16:20] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:24] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:28] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:33] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:40] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:44] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:51] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:16:57] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:03] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:08] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:14] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:19] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:26] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:32] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:37] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:43] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:47] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:17:54] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:00] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:06] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:11] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:15] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:22] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:26] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:33] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:37] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:44] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:48] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:18:54] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:00] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:04] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:11] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:17] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:22] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:28] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:32] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:37] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:44] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:49] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:55] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:19:59] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:05] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:10] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:16] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:20] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
. Unban in: 45/45
[05:20:25] (EVOLVED) Potential Evolutions: 0
[05:20:25] (EGG) Incubator status update: 2.00km left
[05:20:27] (INFO) Amount of Pokemon Seen: 3/151, Amount of Pokemon Caught: 3/151

[05:20:28] (INFO) Traveling to Pokestop: Topiary Golfer (0m) (0 seconds)
[05:20:34] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:39] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:43] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:20:50] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
. Unban in: 4/45
[05:20:55] (SOFTBAN) Successfully bypassed!
[05:20:55] (POKESTOP) Name: Topiary Golfer XP: 50, Gems: 0, Items: 3 x ItemPokeB
all, Lat: 52.555238, Long: -1.73222
[05:20:56] (EVOLVED) Potential Evolutions: 0
[05:20:56] (EGG) Incubator status update: 1.99km left
[05:20:57] (INFO) Amount of Pokemon Seen: 3/151, Amount of Pokemon Caught: 3/151

[05:20:59] (INFO) Traveling to Pokestop: Topiary Golfer (1m) (0 seconds)
[05:21:05] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:21:10] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:21:16] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:21:20] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
[05:21:27] (SOFTBAN) Name: Topiary Golfer INFO: Looting failed, possible softban
. Unban in: 5/45

**Comment by daproject85** [comment]
+1

**Comment by dswtech** [comment]
yes, please fix this, this is is a waste if we're using lucky and incense together ..

**Comment by khairulpetrcech** [comment]
so actually its not a softban?

**Comment by goshslayer** [comment]
@khairulpetrcech in this particular case, no. but still, the bot spam "take pokestop" for 5 min to niantic servers which is really a bot-like behavior.

**Comment by khairulpetrcech** [comment]
So its flag the server..better stay away form 0.9.2 for a while im guess

**Comment by NoxxDev** [comment]
fix in v0.9.4 or upper
