### ISSUE TITLE
0.9.3 Rocket API Errors

### ISSUE THREAD

**Issue by Ev0luti0n2016** [NoxxDev/NecroBot#272]
[xxxxxx] Perfect! You already have the newest Version 0.9.3
[xxxxxx] Logging in using Ptc
[xxxxxx] System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 169
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 38
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 14
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
[11:31:47] Logging in using Ptc
[11:31:47] System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 169
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 38
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 14
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
[11:32:07] Logging in using Ptc
[11:32:07] System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 169
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 38
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 14
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35

**Comment by blackfabs** [comment]
i have problem, I've configured API KEY and after restart necrobot i have message "You need to configure your Google Api Key". What is wrong?

**Comment by Skolzack** [comment]
@blackfabs Same here, and variant walking still bugged ZZZzZzzZZ @NoxxDev

**Comment by RavenHome1** [comment]
check your auth config you might have entered wrong user and password

**Comment by Ev0luti0n2016** [comment]
@RavenHome1 :  If that suggestion was for me, that is not the issue. Works fine in 0.9.2. I have tried to configure setup using a fresh account and going through the NecroBot to start from fresh in 0.9.3 and created a new Google API and kept the config as it was and still get the same error.

@blackfabs :  Did you create a Google API and open your config in notepad and edit the info there?
Look For:
     "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "**ENTER THE GOOGLE API KEY HERE AND KEEP THE QUOTATION MARKS**",
    "Cache": false
  },


...don't forget to save and start the bot.

**Comment by RavenHome1** [comment]
@Skolzack varient walking is working fine, it is just not showing in console, go to config and enable it to show.

**Comment by blackfabs** [comment]
@Ev0luti0n2016 I'm not a stupid i set a right key in the right setting.... I use 0.9.3 in 0.9.2 l'asta Night no problem with api.... There is a problem in necro with api ....me and houdred person have the same problem....

**Comment by Ev0luti0n2016** [comment]
@blackfabs  Sense the same frustration that I have. Intention was to help and I did not think you were stupid. I am not sure if my error is related to the API key, but I have set it to false and still get the same message. I go back to 0.9.2 and no issues. 

I do see that a few things were updated today and not sure if that was included in the 0.9.3 release and I don't know how to add that via git even though I have that installed and used it to make a location map.

**Comment by YouGamePlayHD** [comment]
# **GUYS: AGAIN!**
@blackfabs This is a default message! It will always be displayed, but the google walk will work!

**Comment by Ev0luti0n2016** [comment]
The way that I was able to fix this and get 0.9.3 working is to do the following:

1-Start 0.9.2
2-Accept update
3-DO NOT configure your account -->It will make an empty config
4-Edit the new auth.json and config.json with your info
5-Start the bot
6-Have fun and hope that your account does not get banned
