### ISSUE TITLE
0.8.8 new exception

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#31]
[16:37:06] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:37:07] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()

**Comment by vfuyong** [comment]
Another occurrence:

[16:56:54] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:56:55] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()

**Comment by vfuyong** [comment]
I tried when EnableMissedThrows = 'true' or 'false', both will encounter the above exception.

**Comment by ntatoo** [comment]
@vfuyomg 

that mean your banned or just server down

**Comment by lautpelaut** [comment]
@ntatoo 
not banned but bot can't work again

**Comment by vfuyong** [comment]
This exception is very frequent..please fix.

**Comment by NoxxDev** [comment]
Check if the [v0.9.0] (https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.0) continues with this problem
