### ISSUE TITLE
9.4 Forced stop automatic??

### ISSUE THREAD

**Issue by male2961** [NoxxDev/NecroBot#346]
Good Day !!!

had everyone experience the force closed of the new version 9.4??

anyone plsss help..

thanks

**Comment by maboigorilla** [comment]
my necrobot 0.9.4 keeps crashing right after i open it ..

**Comment by male2961** [comment]
@maboigorilla yeah same here men.. haha..

**Comment by NoxxDev** [comment]
Delete your config.json
@bc12cb77c6ab0c682f897685618b609a049ebeb5

**Comment by male2961** [comment]
@NoxxDev  after we delete?? just a little intructions.. :)

**Comment by maboigorilla** [comment]
sorry @NoxxDev  , config.json could not be created because we can't even start running the bot. It crashes INSTANTLY ..or maybe im just dumb

**Comment by male2961** [comment]
@maboigorilla @NoxxDev yeah hes right anyways!!

**Comment by mjusuf** [comment]
different config v0.9.3 and v0.9.4
v.0.9.3
`  "SoftBanSettings": {
    "FastSoftBanBypass": false,
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": true,
    "AmountPokestops": 80
  },`
v.0.9.4
`  "KillSwitchSettings": {
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": true,
    "AmountPokestops": 80
  },`

edit your config.json

**Comment by maboigorilla** [comment]
Do we use 0.9.3's config.json for 0.9.4?? There is NO config.json on my 0.9.4 folder because necrobot cant run .

**Comment by male2961** [comment]
@anyone ill suggest to used 9.3 for now just turn autoupdate to false

**Comment by mjusuf** [comment]
@male2961 
v.0.9.3 not implement this
https://github.com/NoxxDev/NecroBot/issues/336

**Comment by male2961** [comment]
@mjusuf but im using it just now

**Comment by maboigorilla** [comment]
I will just run 0.9.3 until someone gives me a clear instruction on how to fix it...

**Comment by male2961** [comment]
@maboigorilla did it worked on you??

**Comment by mjusuf** [comment]
@maboigorilla 
if you use config.json from v0.9.3 just change KillSwitchSettings area like this
```
"SoftBanSettings": {
    "FastSoftBanBypass": false
  },
"KillSwitchSettings": {
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": true,
    "AmountPokestops": 80
  },
```

**Comment by maboigorilla** [comment]
@mjusuf  alright ill give it a try :)

**Comment by maboigorilla** [comment]
@mjusuf  didnt work tho

**Comment by male2961** [comment]
@maboigorilla omg

**Comment by maboigorilla** [comment]
@male2961  did it work for you

**Comment by male2961** [comment]
@maboigorilla yep im using it still.. i suggest to reinstall it men and after filling-up user-loc-and pass dont let it run.. just head to config and change the autoupdate and checkupdate to false men..

**Comment by maboigorilla** [comment]
@mjusuf so you are using 0.9.3?

**Comment by male2961** [comment]
@mjusuf yeah still..

**Comment by mjusuf** [comment]
@maboigorilla no, iam using 0.9.4, and nothing problem

**Comment by clash-votter** [comment]
Error log upon starting.

[17:59:50] () Exception caught, writing LogBuffer.

Unhandled Exception: System.TypeInitializationException: The type initializer for 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' threw an exception. ---> Sy
stem.TypeLoadException: Could not load type 'System.Security.Authentication.SslProtocols' from assembly 'System.Net.Primitives, Version=4.0.0.0, Culture=neutral
, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Net.Http.HttpClientHandler..ctor()
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\HttpClient\PokemonClient.cs:line 9
   --- End of inner exception stack trace ---
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\HttpClient\PokemonClient.cs:line 17
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy apiFailureStrategy) in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\C
lient.cs:line 41
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\Session
.cs:line 61
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\Session
.cs:line 36
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

**Comment by male2961** [comment]
@clash what was that??

**Comment by robbigoal** [comment]
im used 0.9.4 run smoothly : download release 0.9.4 >   run > edit config u style

**Comment by clash-votter** [comment]
![image](https://cloud.githubusercontent.com/assets/21138034/17836102/188d92bc-67ca-11e6-9069-eb1ad20bba2a.png)

Here's a screenshot of the error log when it crashes. I applied translation folder fix, same error.

**Comment by maboigorilla** [comment]
@male2961  how did u fix your problem

**Comment by SchraderZhang** [comment]
抱歉插一楼0.0
嘛~有中国人咩？

**Comment by knumchoke** [comment]
`Pokemon Servers might be offline / unstable. Trying again...`
```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
```

got these error after update. some error gone after patched the killswitchsettings.
bot didn,t crash but try to relogin.

**Comment by clash-votter** [comment]
If not related to this problem (9.4 Forced stop automatic??) Pls start new issue thank you.

**Comment by boylondon** [comment]
it works well for me, re-download and install new one,.. configure with old setting

**Comment by inclouis** [comment]
@boylondon how do you configure when the bot crashes and no config shown?

**Comment by boylondon** [comment]
@inclouis no crash in me,.. working properly well, i download new one, and configure like my old configuration

**Comment by clash-votter** [comment]
In earlier versions the exe makes config for you, much better to just edit the config made. With this one it crashes after running exe. 

Explain better pls. Downloaded new one, carried on the config files from previous version ? And bot works with no errors? The error occurs when you run .exe after unzipping release folder. Means it crash before even makes config and auth.

**Comment by boylondon** [comment]
![094](https://cloud.githubusercontent.com/assets/20999994/17836335/b0bc00f8-67b8-11e6-946c-ff5801e67e0f.png)
its my first time use google walk, did it always walk in locked speed 6km/h? and it doesnt walk using gpx as well

**Comment by fede121197** [comment]
i can't use necrobot, when i open it crash immediately

**Comment by kosior98** [comment]
delete NecroBot.exe.config file 
for me its works

**Comment by clash-votter** [comment]
@kosior98 +1 bot starts as expected

**Comment by fede121197** [comment]
@kosior98 thanks now necrobot works

**Comment by maboigorilla** [comment]
OMG DELETING NECROBOT.EXE WORKS THANKS

**Comment by ausscheider** [comment]
or this one -->> https://github.com/NoxxDev/NecroBot/issues/358

**Comment by davidmario** [comment]
deletting necrobot.exe config

**Comment by dodogtg** [comment]
thx @davidmario
