### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by tutti13** [NoxxDev/NecroBot#367]
Randomly getting the following exception with 0.9.4 default config. Bot will then re-login and continue.

[15:39:25] (FEHLER) Pokemon Servers might be offline / unstable. Trying again...
[15:39:26] (FEHLER) Error: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:Zeile 246.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:Zeile 44.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 117.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:Zeile 68.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 57.

**Comment by memiedeedy** [comment]
I have got the same thing like you

***Clear Install from Release094
***Fresh Config and Auth file

[20:43:59] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[20:44:00] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

**Comment by imolesi** [comment]
Same here...
