### ISSUE TITLE
Pokemon Servers might be offline / unstable. Trying again...

### ISSUE THREAD

**Issue by Theo1996** [NoxxDev/NecroBot#368]
### Expected Behavior
no dusrupts in the connection with niantic

### Actual Behavior
Connection to niantic is restarted with the  2 different errors on different occasions below:

`[16:39:38] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:39:39] (ERROR) Error: System.Net.Http.HttpRequestException: Error while copying content to a stream. --->
 System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException
: The connection with the server was terminated abnormally
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncAnyStreamToAnyStreamCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in E:\Projetos\CSharp\
NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in E:\Projetos\
CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__12`1.MoveNext() in E:\Projetos\CSharp\NecroBot\Fer
oxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`6.MoveNext() in E:\Projetos\CSharp\NecroBot\Fer
oxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\Poke
monGo.RocketAPI\Rpc\Map.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__1.MoveNext() in E:\Projetos\CSh
arp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroB
ot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass4_0.<<Execute>b__1>d.MoveNext() in E:\Proj
etos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.HumanStrategy.<Walk>d__7.MoveNext() in E:\Projetos\CSharp\NecroBot\
PoGo.NecroBot.Logic\Strategies\Walk\HumanStrategy.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic
\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoG
o.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroB
ot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.Necro
Bot.Logic\State\StateMachine.cs:line 57`

`
16:38:00] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
16:38:01] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative an
 less than the size of the collection.
arameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resou
ce)
  at System.Collections.Generic.List`1.get_Item(Int32 index)
  at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoG
.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 89
-- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroB
t.Logic\State\FarmState.cs:line 68
-- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.Necro
ot.Logic\State\StateMachine.cs:line 57
16:38:01] (INFO) Logging in using Ptc`

### Your config.json
```
[config txt.txt](https://github.com/NoxxDev/NecroBot/files/428875/config.txt.txt)


```

### Steps to Reproduce
just run the bot an you might get it occasionally, igot 10 in 2hours 40 min

### Other Information

Version:0.9.4
Windows Version:win 7 64 bit ultimate sp1 + newest updates without the botnet

What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
nothoing is really affected but it might be a giveaway to get me banned dont knmopw for sure.

**Comment by kuoliangkwong** [comment]
I got the same error too.
`[21:42:30] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[21:42:31] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Model.Settings.LogicSettings.get_UseKillSwitchCatch() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Model\Settings\LogicSettings.cs:line 109
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass4_0.<<Execute>b__1>d.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__10.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57`








`[21:43:48] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[21:43:50] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Model.Settings.LogicSettings.get_UseKillSwitchPokestops() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Model\Settings\LogicSettings.cs:line 115
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57`


Please fix. Thanks.

**Comment by inclouis** [comment]
I got the same error

**Comment by ShadXo** [comment]
make a backup of your config, open the bot press N, a new config will be created. enter your settings in the new config.

**Comment by inclouis** [comment]
Im using the new config as I re-downloaded 0.9.4 files. I dumped the previous config and files already.

**Comment by ShadXo** [comment]
The error looks like a bad config

**Comment by kuoliangkwong** [comment]
Cool~ deleted the config file and regenerate again seems to work now. Thanks alot. But seems like the autoupdate causes the root cause.

**Comment by Theo1996** [comment]
I did the same with one of the bots and it didnt work,will try with the second one if it works i will report it here.

**Comment by imolesi** [comment]
Same here. Tried different configs (valid json), no solution for me...
Reverted to 0.9.3 but I can't login anymore, it asks for google account even if I set ptc account in auth.json, so far I'm stuck

**Comment by Theo1996** [comment]
@imolesi delte your config AND auth.json might work.

**Comment by ranidentity** [comment]
i got this since this morning and here the error message, i dont think is bad config/auth because yesterday was running fine for me... 

23:51:02] Looking for lure Pokemon...
[23:51:02] (Threw ball) Ordinary hit. Curve-ball...
[23:51:04] Pokemon Servers might be offline / unstable. Trying again...
[23:51:05] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
[23:51:05] Logging in using Ptc

i wonder is it due to the "rare" look for lure pokemon action?
chance to occur is rather low at first, but once it happen, it will come again frequently

**Comment by CrazyKenaz** [comment]
I have the same issue and now I can't log in any more. I don't know it will be a permanent ban or not.
I found my config.json a critical error after update.
The KillSwitchSettings section became null. 
It will cause those error messages when I catch a pokemon or touch a pokestop.
Then bot reboot to default location.

![changetonull](https://cloud.githubusercontent.com/assets/21158694/17838458/bc8e6806-6800-11e6-9ea5-ec443acaf918.jpg)

**Comment by imolesi** [comment]
Thanks @Theo1996 I already recreated the configuration files, but I will try again

**Comment by Theo1996** [comment]
yes,sadly it didn't work.

**Comment by imolesi** [comment]
EUREKA!

Reverting to english language code and disabling the web socket did the trick and now everything is working fine for me.

**Comment by ranidentity** [comment]
hmm, i am using english and web socket false by default... still getting this thing.

is it possible because of my  "EnableMissedThrows": true, ?

**Comment by nutsky** [comment]
i think i have found the cause of error

if you updated from lower version thekillswith settings is nulled. you have to create new killswitch settings

**Comment by ranidentity** [comment]
i use the 1 i downloaded, still having these problems. The killswitch is there.

**Comment by Theo1996** [comment]
@imolsesi nice! , my problem seems to just dissapeared even after deleting transaltion,auth and config it still existed,but now it stopped apearing will update after 2 hours.

**Comment by ranidentity** [comment]
I delete the translation,auth, and config. After awhile get this error sigh...

[21:27:06] Name: Flag Pole at Dataran Merdeka  XP: 50, Gems: 0, Items: 1 x ItemPotion, 2 x ItemGreatBall, Lat: 3.147722, Long: 101.69341
[21:27:07] Pokemon Servers might be offline / unstable. Trying again...
[21:27:08] Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
[21:27:08] Logging in using Ptc

**Comment by Theo1996** [comment]
ny bot is running for 1h30min and i got it once.Seems the problem persists.

**Comment by ranidentity** [comment]
bump?

**Comment by Theo1996** [comment]
0.9.6 solved it no problem here issue closed
