### ISSUE TITLE
Issue on V0.9.4

### ISSUE THREAD

**Issue by helpmeplease1** [NoxxDev/NecroBot#370]
I have run the bot for 1 hour but suddenly having the below error message

[22:32:30] Looking for Pokemon...
[22:32:31] Looking for incense Pokemon...
[22:32:31] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 54

Anyone know what is this? I have setup google API
No issue on Google Maps Directions API	17 (request)

Thank you.

**Comment by NoxxDev** [comment]
Check release v0.9.7
