### ISSUE TITLE
0.9.4 PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext()

### ISSUE THREAD

**Issue by BoydTM** [NoxxDev/NecroBot#383]
### Actual Behavior

[19:42:37] (PKMN) (CatchSuccess) | (Normal) NidoranFemale Lvl: 25 CP: (530/625) IV: 36.00% | Chance: 29.94% | 67.74m dist | with a GreatBall (0 left). | 200 EXP earned | Candies: 1794 | lat: 40.765723 long: -73.973315
[19:42:40] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[19:42:41] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

### Your config.json
```
{
  "ConsoleSettings": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 20,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateSettings": {
    "CheckForUpdates": false,
    "AutoUpdate": false,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsSettings": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
  "LocationSettings": {
    "DisableHumanWalking": false,
    "DefaultLatitude": 40.765087,
    "DefaultLongitude": -73.973144,
    "WalkingSpeedInKilometerPerHour": 10.16,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },
  "TelegramSettings": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": "12345"
  },
  "GPXSettings": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipingSettings": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false
  },
  "PokemonSettings": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 3000,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseEggIncubatorMinKm": 2,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "UseBerriesMinCp": 2500,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 3,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": false,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": true,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 100.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1500,
    "UseUltraBallAboveCp": 2000,
    "UseMasterBallAboveCp": 2500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 100.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 100.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 300,
    "KeepMinIvPercentage": 100.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false
  },
  "RecycleSettings": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "DelayBetweenRecycleActions": false,
    "TotalAmountOfPokeballsToKeep": 120,
    "TotalAmountOfPotionsToKeep": 80,
    "TotalAmountOfRevivesToKeep": 60,
    "TotalAmountOfBerriesToKeep": 50
  },
  "CustomCatchSettings": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 7,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1500,
    "ForceExcellentThrowOverCp": 2000
  },
  "PlayerSettings": {
    "DelayBetweenPlayerActions": 5000
  },
  "SoftBanSettings": {
    "FastSoftBanBypass": false
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "",
    "Cache": false
  },
  "KillSwitchSettings": {
    "UseKillSwitchCatch": false,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": false,
    "AmountPokestops": 80
  },
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": [
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Gastly": {
      "KeepMinCp": 300,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 100,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 400,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1300,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1400,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Dratini": {
      "KeepMinCp": 300,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Dragonair": {
      "KeepMinCp": 500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 8,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}
```

### Steps to Reproduce

Happens (almost always) - before reaching first pokestop

**Comment by imolesi** [comment]
I think it's related to #364 . I have a very similar issue at pokestops, I tried rebuilding config files, no solution for me :-(

**Comment by BoydTM** [comment]
Also tried to repeat error with recently created google account with almost all values = default and at the beggining it worked correctly but after that started to play with some values ( for example "AutoUpdate": true   =>   "AutoUpdate": false) and the same error appear ( maybe some local cache need to be cleared or something like that ... (system restart not helping...). For now going to stay with 0.9.0 (0.9.2 works fine but with higher amount of softbans form time to time (same configuration). Thanks in advance for help in this case ...
