### ISSUE TITLE
I have no idea what this is but it's red text and looks scary

### ISSUE THREAD

**Issue by uncannierelf** [NoxxDev/NecroBot#414]
[06:36:53] Pokemon Servers might be offline / unstable. Trying again...
[06:36:55] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Model.Settings.LogicSettings.get_UseKillSwitchCatch() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Model\Settings\LogicSettings.cs:line 109
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass4_0.<<Execute>b__1>d.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__10.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

**Comment by kiwi1989** [comment]
Hello :)
 "MaxTravelDistanceInMeters" ?

**Comment by uncannierelf** [comment]
@kiwi1989 It's set to the default value. I've tried adjusting it, has not fixed anything.

**Comment by uncannierelf** [comment]
I re-downloaded the Release. Seems to have fixed it.
