### ISSUE TITLE
I have an exception on 0.94

### ISSUE THREAD

**Issue by stjupiter** [NoxxDev/NecroBot#417]
I download version 0.9.4 and Translations.zip done
I extract Translations.zip to Release\Config

Then I run NecroBot,when i answer 'y' it error below

![untitled2](https://cloud.githubusercontent.com/assets/20550589/17855497/29e09986-68a3-11e6-918f-b562d0a1140b.png)

===========Error log ================
[19:52:25] [ERROR] Issue loading translations: Newtonsoft.Json.JsonSerializationException: Error converting value "firstStartSetupDefaultLongPrompt" to type 'PoGo.NecroBot.Logic.Common.TranslationString'. Path 'TranslationStrings[160].Key', line 644, position 47. ---> System.ArgumentException: Requested value 'firstStartSetupDefaultLongPrompt' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PoGo.NecroBot.Logic.Common.Translation.Load(ILogicSettings logicSettings, Translation translations) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Common\Translations.cs:line 899
[19:52:25] [Request] Rebuild the translations folder? Y/N
[19:52:27] Loading fresh translations and continuing
[19:52:27] Exception caught, writing LogBuffer.
===================================================

**Comment by VBQL** [comment]
Redownload the bot, when asking you to change language, say no.

**Comment by imolesi** [comment]
I solved a very similar issue by disabling web socket (no visualizer, sigh) and reverting to english language

**Comment by LightDestory** [comment]
I am using 0.9.4 and no problem, no exception and no error. I don't upgrade the bot, just download the new release.zip and unpack...
I run it and close, i configure the auth.json and config.json using notepad++

**Comment by BoydTM** [comment]
LightDestory - are you catching any lured pokemons ? On my test account it works (almost all values defaulted) however it catches only (normal) pokemon. I am not sure right now if catching lured can be disabled by some parameters or it is just random behaviour ...

**Comment by ausscheider** [comment]
Try this https://github.com/NoxxDev/NecroBot/issues/358

**Comment by BoydTM** [comment]
Already tried. Looks like that in my case everything works fine until encounter with lured pokemon (i believe it's gonna be fixed in next version) - just happen after 1 hour on test account, but before that i had only plenty of the normal ones (which is weird on Pier 39 - place with a lot of lures) so that's the reason of question from my previous comment...

Still - necrobot is great project and appreciation for developers for their work
