### ISSUE TITLE
Every caught pokemon or hit stop

### ISSUE THREAD

**Issue by dhip123** [NoxxDev/NecroBot#419]
[09:29:46] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[09:29:47] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Model.Settings.LogicSettings.get_UseKillSwitchPokestops() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Model\Settings\LogicSettings.cs:line 115
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

gives this error, doesn't stop the bot or anything just weird....

**Comment by YahyahyahCF** [comment]
I'm having the exact same issue, since it updated to 0.9.4

**Comment by dhip123** [comment]
Anyone have a fix for this? I know it might seem fishy logining in every time I catch/hit a pokemon/stop. Also the walking speed after this update only goes +/- 0.1 km any ideas?

**Comment by tws101** [comment]
This is an update issue....

If windows defender or another active virus protection was running during install or update you will have this issue.

Purge your install, kill protection, reinstall.

**Comment by tiggerite** [comment]
The code causing this has been removed now anyway, it seems. (It wasn't in FarmPokestopsTask before I moved the code into UseNearbyPokestopsTask) The line that was causing the crash was checking for session.LogicSettings.UseKillSwitchPokestops.

**Comment by iwean** [comment]
Please update your Framework and Visual C++

**Comment by litex2x** [comment]
This is still an issue in the current release v0.9.4

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
