### ISSUE TITLE
problem running bot please help

### ISSUE THREAD

**Issue by addisonrudd** [NoxxDev/NecroBot#553]
this is what im getting. I cant be banned because i JUST made the account.
[15:55:34] (INFO) Your IP is: 108.75.122.190
[15:55:35] (UPDATE) Perfect! You already have the newest Version 0.9.6
[15:55:35] (INFO) Logging in using Google
[15:55:36] (INFO) System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.Crypt.LoadFunction[T](String dllPath, String functionName) in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\Crypt.cs:line 31
   at PokemonGo.RocketAPI.Helpers.Crypt..ctor() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\Crypt.cs:line 13
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 37
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 14
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35

**Comment by Skolzack** [comment]
Need to be like that below:

"AuthConfig": {
    "AuthType": "ptc",
    "GoogleUsername": null,
    "GooglePassword": null,
    "PtcUsername": "youregay",
    "PtcPassword": "123456"

} ,

**Comment by addisonrudd** [comment]
@Skolzack thats how i did it

**Comment by Skolzack** [comment]
@addisonrudd Delete auth.json, open necro and config it again.

**Comment by addisonrudd** [comment]
@Skolzack does it matter that i dont have a proxy set?

**Comment by Skolzack** [comment]
@addisonrudd No

**Comment by addisonrudd** [comment]
@Skolzack it says my "ptr" cant be null. idk what that is

**Comment by Skolzack** [comment]
As I said, delete auth.json and config.json then open necro and try again....

**Comment by addisonrudd** [comment]
@Skolzack i did that. same error
