### ISSUE TITLE
You are catching too fast.

### ISSUE THREAD

**Issue by MaartenDeen** [NoxxDev/NecroBot#607]
Hmm, what is this error? Is this Niantic?
[21:36:47] You are catching too fast. Your cannot catch another one until 12679 seconds later

I was not catching that fast, 40 P/H. Would be a bummer if I really have to wait 3,5 hours.

**Comment by NoxxDev** [comment]
CatchLimit

```
    "UseCatchLimit": true,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
```

**Comment by iPollox** [comment]
I got the same thing, I just woke up and my bot has been spamming that for the past 5 to 6 hours actually, I just closed the bot to be sure until the next released. @NoxxDev

**Comment by iPollox** [comment]
```
[11:08:44] Error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'pgorelease.nianticlabs.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetIncensePokemons>d__2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Map.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchIncensePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchIncensePokemonsTask.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass8_0.<<FortPokestop>b__0>d.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 205
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.BaseWalkStrategy.<DoWalk>d__14.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\BaseWalkStrategy.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FortPokestop>d__8.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__7.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
[11:08:44] Logging in using Ptc
[11:08:55] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'sso.pokemon.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
```
The bot relogged itself and then this happened:
```
[11:09:15] Logging in using Ptc
[11:09:16] Playing as <REMOVED NAME>
[11:09:17] Detected realistic Traveling , using Default Settings inside config.json
[11:09:17] Make sure Lat & Lng are right. Exit Program if not! Lat: <REMOVED> Lng: <REMOVED>
<REMOVED PERSONAL LOG>
[11:09:57.085] Looking for Pokemon...
[11:09:57.733] Looking for incense Pokemon...
[11:09:59.027] Looking for Pokemon...
[11:09:59.679] Looking for incense Pokemon...
[11:10:01.047] Looking for Pokemon...
[11:10:02] You are catching too fast. Your cannot catch another one until 37598 seconds later
```

The last log is:
`[16:08:09] You are catching too fast. Your cannot catch another one until 19712 seconds later
[16:08:11] You are catching too fast. Your cannot catch another one until 19709 seconds later
[16:08:14] You are catching too fast. Your cannot catch another one until 19707 seconds later
[16:08:16] You are catching too fast. Your cannot catch another one until 19705 seconds later
[16:08:16.303] Looking for incense Pokemon...
[16:08:17.405] Looking for Pokemon...
[16:08:18] You are catching too fast. Your cannot catch another one until 19702 seconds later
[16:08:20] You are catching too fast. Your cannot catch another one until 19700 seconds later
[16:08:23] You are catching too fast. Your cannot catch another one until 19698 seconds later
[16:08:25] You are catching too fast. Your cannot catch another one until 19695 seconds later
[16:08:25.517] Looking for incense Pokemon...
[16:08:25.792] Looking for Pokemon...
[16:08:26] You are catching too fast. Your cannot catch another one until 19694 seconds later
[16:08:29] You are catching too fast. Your cannot catch another one until 19692 seconds later
[16:08:31] You are catching too fast. Your cannot catch another one until 19689 seconds later
[16:08:33] You are catching too fast. Your cannot catch another one until 19687 seconds later
[16:08:33.987] Looking for incense Pokemon...
[16:08:34.931] Looking for Pokemon...
[16:08:36] You are catching too fast. Your cannot catch another one until 19685 seconds later
[16:08:38] You are catching too fast. Your cannot catch another one until 19683 seconds later
[16:08:40] You are catching too fast. Your cannot catch another one until 19680 seconds later
[16:08:43] You are catching too fast. Your cannot catch another one until 19678 seconds later
[16:08:43.075] Looking for incense Pokemon...
[16:08:44.184] Looking for Pokemon...
[16:08:53] You are catching too fast. Your cannot catch another one until 19676 seconds later`

5 Hours so far the bot has been doing that. @NoxxDev

**Comment by CreativiTimothy** [comment]
@NoxxDev @iPollox I agree with iPollox. I set it at 990 Pokemon, but after 400 Pokemon, it started spamming "catching too fast". The pokemon/pokestop limit seems very buggy at the moment, so it's best to not use it until there's a new release with a bug fix

**Comment by iPollox** [comment]
Yeah, and I've this bot run 24 hours straight at one point and never saw this until now.

**Comment by CreativiTimothy** [comment]
@NoxxDev I have a suggestion to fix this. In the config, let the user set how many Pokemon/Pokestops he/she already caught/spun at the time. Basically, let the user set the starting counter. The bot seems to mess up really badly at the starting counter (seems to start at 500 for pokemon or something).

For example:   
    "UseCatchLimit": true,
    "CatchLimitStartingCounter": 0
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,

This basically means that the user caught 0 pokemon in the last 24.5 hours, so the user put 0 as the starting counter.

**Comment by MaartenDeen** [comment]
I set CatchLimit to false and that solved it. I agree with previous comments that this does not seem to be handled correctly. 
If this is set to true, put in the logs how many you have caught (with the (INFO) lines).
