### ISSUE TITLE
Google authentication error

### ISSUE THREAD

**Issue by yonathanbrazil** [NoxxDev/NecroBot#725]
Yes, my **auth.json** is fine, with the code for two step.
I really can't figure out why I can't login.

```
[18:38:10] Perfect! You already have the newest Version 0.9.7
[18:38:10] Logging in using Google
[18:38:10] Your IP is: XXXX
[18:38:11] PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exception of type 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
[18:38:31] Logging in using Google
```

With Google API Key:

```
[18:43:02] PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exception of type 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
[18:43:22] Logging in using Google
Initializing NecroBot logger at time 8/30/2016 6:46:27 PM...
[18:46:33] Exception caught, writing LogBuffer.
```

**Comment by Skolzack** [comment]
Delete or backup the old config.json, let the necrobot create a new one and see if works.

**Comment by yonathanbrazil** [comment]
I tried this before, doesn't works.
Actually, I never could login with google account, works well with ptc o/

**Comment by Skolzack** [comment]
Cola aqui como você ta colocando o seu auth.json pra te ajudar melhor.. Não esqueça das aspas "xxxx"

**Comment by Skolzack** [comment]
Desativa autoupdate, checkupdate no config.json tambem

**Comment by yonathanbrazil** [comment]
Já revisei tudo várias vezes, esse problema tinha deste a versão oficial 0.8.6...
Sim, não esqueci nada no json, inclusive para medida de teste se eu não uso o código autenticador do google ele reconhece que tem "two step" e fecha com aviso para colocar o código. Logo, ele passa por todas as outras linhas do código., também por isso ao desativar autoupdate e/ou checkupdate não interfere, esse método é chamado antes. Mesmo assim testei de novo agora e o problema persiste...
Sempre faco uma fresh install, e estou usando a config default, não editei nada!


```
{
  "AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "xxx",
    "GooglePassword": "xxx",
    "PtcUsername": "null",
    "PtcPassword": "null"
  },
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePackageName": "galaxy-s7-edge",
    "DeviceId": "c2827e08ef938f54",
    "AndroidBoardName": "msm8996",
    "AndroidBootloader": "G935TUVU3APG1",
    "DeviceBrand": "samsung",
    "DeviceModel": "SM-G935T",
    "DeviceModelIdentifier": "hero2qltetmo",
    "DeviceModelBoot": "qcom",
    "HardwareManufacturer": "samsung",
    "HardwareModel": "SM-G935T",
    "FirmwareBrand": "hero2qltetmo",
    "FirmwareTags": "release-keys",
    "FirmwareType": "user",
    "FirmwareFingerprint": "samsung/hero2qltetmo/hero2qltetmo:6.0.1/MMB29M/G935TUVU3APG1:user/release-keys"
  }
}
```

**Comment by Skolzack** [comment]
Criou uma outra conta gmail só pra testar? Ou entre nessa conta gmail que vc ta tentando usar e vê se ta pedindo pra confirmar identidade, enviar sms pra algum numero etc

**Comment by yonathanbrazil** [comment]
Eu uso essa conta a muitos anos, inclusve é google business

**Comment by Skolzack** [comment]
Tenta com uma outra conta gmail.. vê se funciona

**Comment by yonathanbrazil** [comment]
Sim, funciona, eu não ativei o two step, mas já testei desativando o da minha conta principal e resultava no mesmo erro.
E como não tenho como transferir os pokemons, XP, tudo, ai perde toda a lógica :/
Será que alguma coisa administrativa esta impedindo este login, agora, o que, pois consigo logar pelo app normalmente...

**Comment by Skolzack** [comment]
Provavelmente.. essa sua conta ai tem alguma segurança a mais que o necro não ta reconhecendo ou por ela ser business, sei la..

**Comment by yonathanbrazil** [comment]
Em parte isso foi bom, pois as outras contas de ptc que usei desde o incio foram banidas hahaha.
As atuais com essa versão, human walk, funcionam super bem! Tudo ok rodando a dias.
Agora penso o que será que esta influenciando isso?

**Comment by Skolzack** [comment]
Você só irá encontrar a resposta entrando em contato com algum dos caras que estão fazendo a manutenção do Necro, eles vão saber te responder melhor

**Comment by yonathanbrazil** [comment]
Bah, eu to com uma outra conta lvl 25 e outrqa 23, em ips diferewntes, to com medo de deixar rodando no mesmo ip e identificarem e dar ban. Será? O ip mudo fácil, agora perder a conta leva um seculo de novo pra subir de lvl.
