### ISSUE TITLE
Getting this Error Message when using PTC accounts

### ISSUE THREAD

**Issue by Dopey422** [NoxxDev/NecroBot#762]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior

Hi, I am trying to login with my PTC account and I receive the following message:
`[12:20:48] (UPDATE) Perfect! You already have the newest Version 0.9.7
[12:20:48] (INFO) Logging in using Ptc
[12:20:48] (INFO) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
[12:20:48] (INFO) Your IP is: 24.176.193.242`

I do NOT get this message when logging into my google accounts.

### Your config.json
```
{
  "AuthConfig": {
    "AuthType": "ptc",
    "GoogleUsername": null,
    "GooglePassword": null,
    "PtcUsername": "username",
    "PtcPassword": "pw"
```

### Other Information
Version: 9.7
Windows Version: Windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Logging in

**Comment by Skolzack** [comment]
You can login on your PTC account on phone? If can't youre banned

**Comment by Dopey422** [comment]
Skolzack, Yes I can log in fine to my PTC account fine on my phone

**Comment by moo23** [comment]
PTC server is just down or having server issues

**Comment by grinmind** [comment]
try backing up your config, then run the setup on necro for it to create a new config, then run if it works, then you have a problem with your config
