### ISSUE TITLE
CatchMissed and CatchFlee

### ISSUE THREAD

**Issue by owenchai1989** [NoxxDev/NecroBot#805]
Catch pokemon showing up all are CatchMissed and CatchFlee.. what happening??

**Comment by owenchai1989** [comment]
how to solve?

**Comment by LobsterX** [comment]
IP ban only results in a blank map. no pokestop, no gym. no pokemons

Catchmissed is nothing. dun worry about it

catchflee. if this occurs at first pokemon captureing attempt for all pokemons encountered, you've probally soft banned due to location. YOU TELEPORTED OR MOVED TOO FAST.

that's all. just wait it out and dun play the game for 1hr~8hrs

this might also mean your account is flagged for perm ban

**Comment by owenchai1989** [comment]
so my account get soft ban(IP) of this that mean i cnt bot again after unsoft ban?? if continue bot will getting perm ban?

**Comment by XilverX** [comment]
"so my account get soft ban(IP) of this that mean i cnt bot again after unsoft ban?? if continue bot will getting perm ban?"

after soft ban is removed you can bot again... 
even if you haven't experience this keep in mind botting has a very big chance of ban...
also, even if you don't open your account that you're botting, when Niantic do a ban wave and your account fits the criteria, it will be banned... 

just pray that you won't get caught and after getting to level25~30 stop botting...

**Comment by owenchai1989** [comment]
this softban has gone.. but now come a next problem as below... wtf..




[07:16:33] Pokemon Servers might be offline / unstable. Trying again...
[07:16:34] Error: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 14
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
