### ISSUE TITLE
Human Walk Snipe - Data feed is wrong.

### ISSUE THREAD

**Issue by samuraitruong** [NoxxDev/NecroBot#846]
hi Guys,

That may happen to you too. I got this issue first time today.  Datafeed from pokeradar is absolutely today. I try to use nox player to find pokemon that them report is spawning but they are all fake. even I moving around the area still not show up. I think those guys report because was had same issue to me this morning. 

SO, this is time to implement this feature work with pokemon local map :)) won't take long.

**Comment by iwean** [comment]
Can't wait :+1:  :smiley:

**Comment by BoydTM** [comment]
Account itself will gather spawn data from surrounding area ? Are we know what is the range of the scans performed by the pokemon app during normal gameplay ? (it may be rather limited ... )

**Comment by Ev0luti0n2016** [comment]
I have been having an issue today as well with Human Snipe after updating from the Master. Necro crashes and it is going to a location that is not even near me **(I have put the coordinates in BOLD)**. I do not have telegram on and have stopped using GPX because of it warping back to pokestops. 

Is it possible to add verified pokezz to the list? 

**Here is my error that stops Necro:**
[xx:xx:xx] (HUMAN WALK) Found 3 pokemon matched with you filters. Human walking sniper won't catch em all. but try to maximun catch if possible.
[xx:xx:xx]      Source      |  Name               |    Distance    |   Expires        |  Travel times   | Catchable
[xx:xx:xx]  Pokesnipers      |  Dratini           |  0.00m  	|  02 min 47 sec  |  00 min 15 sec  | Possible
[xx:xx:xx]  Pokesnipers      |  Electabuzz        |  0.00m  	|  08 min 39 sec  |  00 min 15 sec  | Possible
[xx:xx:xx]  Pokesnipers      |  Slowbro           |  0.00m  	|  07 min 08 sec  |  00 min 15 sec  | Possible
[xx:xx:xx] (HUMAN WALK) Found Dratini spawning | lat: **-27.064073, lng: -70.82412,** dist 0.00m , expired in 03 min 46 sec | Estimate : 00 min 15 sec | Allow spin: No | Allow catch : No | Speed 4.12km/h
[xx:xx:xx] Pokemon Servers might be offline / unstable. Trying again...
[xx:xx:xx] Error: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 19
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk.Get(GoogleResult googleResult) in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 60
   at PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<Execute>d__12.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__11.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in X:\xxx\xxx\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

**Config**
  },
  "WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": xx.xxxxx,
    "DefaultLongitude": xx.xxxx,
    "WalkingSpeedInKilometerPerHour": 4.20,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.20,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 5000
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": "12345"
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39
  },
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 10,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": false,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": false,
    "PokeStopLimit": 1998,
    "PokeStopLimitMinutes": 2000
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "DefaultStepLength": 1.5,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "XXXXXXXXXXXXX",
    "Cache": false

  },
  "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "raichu",
      "arcanine",
      "poliwrath",
      "machamp",
      "slowbro",
      "muk",
      "hitmonchan",
      "gyarados",
      "lapras",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dratini",
      "dragonair",
      "dragonite",
      "mewtwo",
      "mew"
    ]

Human Walk Sniper Filter is default config 


@NoxxDev , @iwean , @jjskuld - Thanks for all of your work and collaboration on this project :)

**Comment by mo0ojava** [comment]
@samuraitruong Seen something like that a while ago. Had two accounts running and *one* of them ended up with missing snipe-targets. The other one picked them up just fine. "At home" they both took stops and local Pokes with no problems. Rather strange.

a) it was IP-related, or
b) it was account-related

Not seen any other reports of this though.

**Comment by mo0ojava** [comment]
Since yesterday I've also been having problems with empty maps when using VPN in some areas. Others work.
Maybe N did something on their end regarding ip-restrictions?

**Comment by samuraitruong** [comment]
I got it working again with data feed from fastpokemap.se, however, my code now is a bunch of changes so it hard to do PR :) you guys can get source for my develop branch or master branch.

**Comment by samuraitruong** [comment]
pokezz already in human snipe
`
FetchFromFastPokemap(lat, lng),
                //FetchFromPokeWatcher(lat, lng),
                FetchFromPokeradar(lat, lng),
                FetchFromSkiplagged(lat, lng)     ,
                FetchFromPokecrew(lat, lng) ,
                FetchFromPokesnipers(lat, lng)  ,
                FetchFromPokeZZ(lat, lng)
`

**Comment by mo0ojava** [comment]
What did you change?

**Comment by samuraitruong** [comment]
No, I just add new data feed get feed from fastpokemap.se. it work for now . good replacement when pokeradar is provide not trust able feed today.

**Comment by Silph-Road** [comment]
another solution, that might work, but i dont know, how safe it is:

Teleport bot to snipe target pokemon location
Verify spawn and then teleport back (without doing anything with pokemon or pokestops).
Start to walk towards confirmed pokemon.

From my understanding, if you dont spin pokestop or catch pokemon after teleporting and then teleporting back, you never get a softban, cuz nothing happened. 

Not sure how it works in terms of API, but just a thought. 

Maybe we can use it for when bot finds a pokemon 2500m+ away

**Comment by V3LL** [comment]
@samuraitruong Thank you for the awesome work you doing. 
I have asked before for this, but going to re-ask just in case you forgot: Please add localhost feed data (from pogofeeder/msnipper) to humanSniper. That way we can have the pogofeeder validating spawns, plus getting IV and Moves info as well.
If possible, transfer/duplicate all of long range sniper functionality (SnipeIgnoreUnknownIv, SnipePokemonNotInPokedex,UseTransferIvForSnipe) into humanSniper.

It would be nice if you could make a setting to choose our snipping method too (like enable both, disable longRange etc)

Thanks again. HumanSnipper is a truly brilliant idea.

**Comment by Silph-Road** [comment]
Yeah seriously, the devs are awesome on this project.
I do think that we need a "Pokemon To Ignore" filter based on their CP, IV, Moveset, LVL. This will allow the bot to skip catching certain rare pokemon based on a chosen stat. 
The key is to not catch everything and then transfer them, as it builds up a lot of candies. This is very suspicious and tells niantic that a person is botting, especially when they have 200 snorlax candies and 200 lapras candies etc.

It would be helpful to make to a setting for each pokemon like:

"Snorlax": {
"UseCatchMin": true,
"CatchMinLvl": 20,
"CatchMinCP": 2000,
"CatchMinIV": 90,
"CatchMoves": [],
"CatchMinOperator": "or",
"CatchMovesOperator": "or"
"KeepMinCp": 10,
"KeepMinLvl": 22,
"UseKeepMinLvl": true,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 40,
"Moves": [],
"DeprecatedMoves": [],
"KeepMinOperator": "or",
"MovesOperator": "or"
},

Reference issue: [https://github.com/NoxxDev/NecroBot/issues/823](https://github.com/NoxxDev/NecroBot/issues/823)

**Comment by Captain024** [comment]
How can we fix this problem? The sniper seems to go to locations where the pokemon doesn't spawn..

**Comment by Brazuca87** [comment]
Something broke the PokeSnipers feed, as it always grabs location as your current location (showing distance 0.00m).

This is crashing the bot every time

**Comment by samuraitruong** [comment]
I still think that risky to do teleport. however, I will add feature allow you use it at your risk.
below feature will be added

- allow every pokemon spaw before walking
- filter by CP/IV for snipe walk


but, It will be very risky to use this 

pokesnipers was down yesterday. I will check data feed later

**Comment by Brazuca87** [comment]
The data being fed is good. Maybe they changed the format or something, but the data seems good. It was working fine until a few commits ago though, so I think someone broke it.

What I also noticed is that someone broke the Human Snipe to always use Base Walk, for some reason... This is getting annoying :(

**Comment by Silph-Road** [comment]
@samuraitruong awesome! Thanks! :-)
We can test and see if it bans accounts if we teleport.  Thanks! (its like the middle path between pure snipe and walk sniping)

The filter by CP/IV for snipe walk, is it specific for each pokemon? 
because if it is a global setting for all pokemons, it would be very hard to catch anything. 
reference: [[REQUEST] Filter: CatchOnlyAboveIv](https://github.com/NoxxDev/NecroBot/issues/823)

**Comment by jjskuld** [comment]
By the way any errors with:
```
PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult)
```
are a dup of #862, which is fixed in master.

**Comment by Ev0luti0n2016** [comment]
@Captain024 
   "How can we fix this problem? The sniper seems to go to locations where the pokemon doesn't spawn.."

   I am having issues with this as well and going to locations that are in different countries now. I am only using human walk.
