### ISSUE TITLE
[BUG] No config run crashes

### ISSUE THREAD

**Issue by Brazuca87** [NoxxDev/NecroBot#868]
Bot crashes when attempting to run without any configs with latest commits.

Log:
[20:42:19] () Exception caught, writing LogBuffer.

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in C:\Users\Documents\Pokemon\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 19
   at PoGo.NecroBot.Logic.Model.Google.GoogleWalk.Get(GoogleResult googleResult) in C:\Users\Documents\Pokemon\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:line 60
   at PoGo.NecroBot.Logic.Model.Google.Teste.Testar(ISession session) in C:\Users\Documents\Pokemon\PoGo.NecroBot.Logic\Model\Google\Teste.cs:line 15
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\Documents\Pokemon\PoGo.NecroBot.CLI\Program.cs:line 164
Press any key to continue . . .

If I run with my old config, I cannot run because apparently a stupid config is now required:
Required properties are missing from object: PokemonUpgradeFilters.

@NvZ
@NoxxDev

**Comment by Brazuca87** [comment]
Well, seems this is happening due to exceeding the daily quota for Google Walk...  Which seems to be exceeded by the latest commits as well (never ran out of my daily quota before).

This is bad... Quota exceeded in less than 4 hours...

**Comment by jjskuld** [comment]
This is also bad error handling on Google side. It's supposed to fall back to other walk methods in error.  Will try to investigate and fix this when k get a chance

**Comment by jjskuld** [comment]
Fixed in 74329c86d14241e153671bd283882c65b6f11a7e.
