### ISSUE TITLE
Error: System.ArgumentOutOfRangeException: Value to add was out of range.

### ISSUE THREAD

**Issue by strife005** [NoxxDev/NecroBot#915]
Hi,

Whenever the config "HumanWalkSnipeConfig" is enabled, the following exception is thrown after botting for a few minutes, tried using the default config but it didn't solve the problem. 

`[22:58:08] Pokemon Servers might be offline / unstable. Trying again...
[22:58:09] Error: System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<>c.<ApplyFilter>b__11_0(SnipePokemonInfo p) in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 115
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.ApplyFilter(List`1 source) in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 115
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.PostProcessDataFetched(IEnumerable`1 pokemons, Boolean displayList) in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 369
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.FetchData(Double lat, Double lng, Boolean silent) in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 295
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.GetNextSnipeablePokemon(Double lat, Double lng, Boolean refreshData) in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 234
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<Execute>d__12.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
`

**Comment by iwean** [comment]
Can I see your config?

**Comment by Hyperhk** [comment]
i dont use humanwalk sniping and still get this error

**Comment by Brazuca87** [comment]
Are you sure you don't use it? This is usually related to finding a list of pokemons and attempting to snipe with 0.0m (current bug for PokeSnipers and PokeWatchers, if used)
